name: Pull Request

on:
  # Trigger analysis when pushing in main or pull requests, and when creating a pull request.
  push:
    branches:
      - main
      - stable
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  publish_to_stable:
    if: ${{ github.ref_name == 'stable' }}
    name: Publish to UAT
    uses: ./.github/workflows/project_build.yaml
    with:
      deploy-env: stable
      publish: true
    secrets: inherit

  build:
    name: Build - Test
    if: ${{ github.ref_name != 'stable' }}
    uses: ./.github/workflows/project_build.yaml
    with:
      deploy-env: prod
      publish: false
    secrets: inherit
