name: Common Publish

on:
  workflow_call:
    inputs:
      timeout-minutes:
        required: false
        type: number
        default: 60
      deploy-env:
        required: true
        type: string
        default: qual
      publish:
        required: true
        type: boolean
        default: false

jobs:
  project_build:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    environment: ${{ inputs.deploy-env }}
    permissions:
      id-token: write
      contents: read
      actions: read
      checks: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      ##############################
      # Build & deploy
      ##############################
      # Get access to github repository
      - uses: actions/checkout@v4
        id: checkout
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Run Unit Tests
        run: pnpm test
        shell: bash

      - name: Run linter
        run: pnpm lint
        shell: bash

      - name: Run build
        env:
          GTAG: ${{ secrets.GTAG }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          ZOHO_ID: ${{ secrets.ZOHO_ID }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        run: pnpm build
        shell: bash

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy to VPS
        if: ${{ inputs.publish == true }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
          echo "Pushing the build app to the remote server"
          scp -o StrictHostKeyChecking=yes -r ./.next/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:/home/${{ secrets.SSH_USER }}/${{ inputs.deploy-env }}/.next
        shell: bash

      - name: Restart the audiolinx-${{ inputs.deploy-env }} process on server
        if: ${{ inputs.publish == true }}
        run: |
          echo "Restarting the audiolinx-${{ inputs.deploy-env }} process on server..."
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} "source ~/.nvm/nvm.sh; cd ${{ inputs.deploy-env }}; git pull; pnpm i; pm2 restart audiolinx-${{ inputs.deploy-env }}; exit"
        shell: bash
